version: '3.8'

services:
  app:
    image: onelots/showcase-roms:latest
    ports:
      - "3000:8000"
    environment:
      NODE_ENV: production
    volumes:
      - /media/hdd/data/EvolutionX/:/app/downloads/

